### PR TITLE
Perfil usuarios

### PR DESCRIPTION
**Pull request by danielcaicedo98**
adding profile query settings and profile photo change

### CODE REVIEW

**Comment by danielcaicedo98** [comment]
adding profile query settings and profile photo change

**Comment by danielcaicedo98** [comment]
there were code integration problems due to a name change in variables belonging to the graphical interface but the conflicts between the branches were successfully resolved

**Comment by CamilaSanchez0** [comment]
Buen trabajo

**Comment by DylanJo2002** [comment]
Hubieron errores debido al cambio del código ya hecho, pero se pudieron sortear. Muy bien.

**Pull request merged**
